"""Flask entrypoint for the AUTOFLOW AI web application."""

from __future__ import annotations

from pathlib import Path

from flask import Flask, jsonify, render_template, request, url_for, send_from_directory

from debugger import check_code
from analyzer import detect_domain_theme
from flowchart import generate_flowchart
from text_diagram import generate_text_diagram, extract_natural_language

BASE_DIR = Path(__file__).resolve().parent
STATIC_DIR = BASE_DIR / "static"

app = Flask(__name__, template_folder="templates", static_folder="static")


@app.route("/")
def index() -> str:
    """Render the single-page interface."""
    return render_template("index.html")


@app.route("/download/<path:filename>")
def download(filename: str):
    """Force download of the flowchart image."""
    return send_from_directory(STATIC_DIR, filename, as_attachment=True, download_name="autoflow-architecture.png")


@app.post("/api/text/analyze")
def analyze_text_new():
    """Analyze text and suggest diagram type with extracted steps."""
    payload = request.get_json(silent=True) or request.form
    text = str(payload.get("text", "")).strip()
    
    if not text:
        return jsonify({"steps": [], "suggestion": {"type": "", "reason": "No text provided."}})
        
    try:
        extractedStr = extract_natural_language(text)
        # Split into steps based on the arrows generated by extract_natural_language
        steps = [s.strip() for s in extractedStr.split("->") if s.strip()]
    except Exception as exc:
        steps = [text]

    step_count = len(steps)
    lower_text = text.lower()
    
    if step_count > 5:
        diagram_type = "Circular Diagram"
        reason = "Multiple steps detected"
    elif "if" in lower_text or "else" in lower_text:
        diagram_type = "Flowchart"
        reason = "Conditional logic detected"
    else:
        diagram_type = "Block Diagram"
        reason = "Sequential process detected"
        
    return jsonify({
        "steps": steps,
        "suggestion": {
            "type": diagram_type,
            "reason": reason
        }
    })

@app.post("/api/text/generate")
def generate_text_diagram_backend():
    """Generate infographic directly from steps array."""
    payload = request.get_json(silent=True) or request.form
    steps = payload.get("steps", [])
    diagram_type = str(payload.get("type", "Flowchart")).strip()
    theme = str(payload.get("theme", "Dark Developer")).strip()
    detail_mode = str(payload.get("detail_mode", "Simplified")).strip()

    from text_diagram import simplify_steps
    if detail_mode == "Simplified":
        steps = simplify_steps(steps)

    if not steps:
        return jsonify({"success": False, "error": "Please provide steps content.", "flowchart_path": ""}), 400

    flowchart_path = ""
    flowchart_error = ""

    from text_diagram import generate_multi_diagram
    try:
        generated_path = Path(generate_multi_diagram(steps, diagram_type=diagram_type, output_dir=str(STATIC_DIR), theme=theme))
        flowchart_path = url_for("static", filename=generated_path.name)
    except Exception as exc:
        flowchart_error = f"Diagram generation failed: {exc}"

    return jsonify({
        "success": bool(flowchart_path),
        "error": flowchart_error,
        "image_path": flowchart_path, # Provide explicitly
        "flowchart_path": flowchart_path, # Keep for legacy compatibility 
        "flowchart_error": flowchart_error,
    })

@app.post("/analyze")
def analyze() -> tuple[object, int] | object:
    """Analyze code and suggest a flowchart style."""
    payload = request.get_json(silent=True) or request.form
    code = str(payload.get("code", "")).strip()

    if not code:
        return jsonify({"suggestion": ""})

    suggestion = "Simple Flowchart"
    try:
        import ast
        tree = ast.parse(code)
        
        has_loop = any(isinstance(node, (ast.For, ast.While)) for node in ast.walk(tree))
        has_condition = any(isinstance(node, ast.If) for node in ast.walk(tree))
        
        if has_loop:
            suggestion = "Detailed Flowchart"
        elif has_condition:
            suggestion = "Decision Flowchart"
    except Exception:
        pass # Fallback to simple if syntax error is currently active

    return jsonify({"suggestion": f"Recommended: {suggestion}"})


@app.post("/generate")
def generate() -> tuple[object, int] | object:
    """Validate Python code, run it, and optionally build a flowchart."""
    payload = request.get_json(silent=True) or request.form
    code = str(payload.get("code", "")).strip()
    language = str(payload.get("language", "Python")).strip()
    theme = str(payload.get("theme", "Dark Developer")).strip()
    style = str(payload.get("style", "Simple")).strip()
    detail_mode = str(payload.get("detail_mode", "Simplified")).strip()

    if not code:
        return (
            jsonify(
                {
                    "success": False,
                    "error": "Please paste code before running AUTOFLOW AI.",
                    "traceback": "",
                    "stdout": "",
                    "flowchart_path": "",
                    "flowchart_error": "",
                }
            ),
            400,
        )

    flowchart_path = ""
    flowchart_error = ""
    
    if language.lower() != "python":
        from language_parser import extract_steps
        from text_diagram import simplify_steps, generate_multi_diagram
        
        extracted = extract_steps(code, language)
        if detail_mode == "Simplified":
            extracted = simplify_steps(extracted)
            
        try:
            generated_path = Path(generate_multi_diagram(extracted, diagram_type="Flowchart", output_dir=str(STATIC_DIR), theme=theme))
            flowchart_path = url_for("static", filename=generated_path.name)
            debug_result = {
                "success": True,
                "error": "",
                "traceback": "Traceback is only available for Python execution.",
                "stdout": f"Logic successfully extracted and parsed for {language}."
            }
        except Exception as exc:
            flowchart_error = f"Diagram generation failed: {exc}"
            debug_result = {
                "success": False,
                "error": flowchart_error,
                "traceback": "",
                "stdout": ""
            }
    else:
        # Fallback to existing python pipeline
        from language_parser import extract_steps
        from text_diagram import simplify_steps, generate_multi_diagram
        
        debug_result = check_code(code)
        
        try:
            # We can use the new logic extractor to unify all flowcharts easily.
            extracted = extract_steps(code, language)
            if detail_mode == "Simplified":
                extracted = simplify_steps(extracted)
                
            generated_path = Path(generate_multi_diagram(extracted, diagram_type="Flowchart", output_dir=str(STATIC_DIR), theme=theme))
            flowchart_path = url_for("static", filename=generated_path.name)
        except SyntaxError as exc:
            flowchart_error = f"Flowchart could not be generated: {exc.msg} on line {exc.lineno}."
        except RuntimeError as exc:
            flowchart_error = str(exc)
        except Exception as exc:  # pragma: no cover
            flowchart_error = f"Unexpected flowchart error: {exc}"

    return jsonify(
        {
            "success": bool(debug_result["success"]),
            "error": "" if debug_result["success"] else str(debug_result["error"]),
            "traceback": "" if debug_result["success"] else str(debug_result["traceback"]),
            "stdout": str(debug_result["stdout"]),
            "flowchart_path": flowchart_path,
            "flowchart_error": flowchart_error,
        }
    )


if __name__ == "__main__":
    import logging
    # Suppress werkzeug request logging to avoid clutter, optional but good for clean terminal
    logging.getLogger("werkzeug").setLevel(logging.ERROR)
    
    # Suppress the Flask development warning
    try:
        from flask import cli
        cli.show_server_banner = lambda *args, **kwargs: None
    except Exception:
        pass
        
    print(" * Serving AUTOFLOW AI successfully!")
    print(" * Running on http://127.0.0.1:5002 (Press CTRL+C to quit)")
    
    app.run(host="127.0.0.1", port=5002, debug=False)
